version: "3"

services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Strong#Pass#1234
    command: server --console-address ":9001" /data

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data


  app: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
      - minio
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development


volumes:
  gem_cache:
  minio_storage: {}
  postgres_db:
    driver: local
